### ISSUE TITLE
Extension is not available in Firefox Add-On Store

### ISSUE THREAD

**Issue by bramus** [bramus/mastodon-profile-redirect#2]
Firefox also supports v3 manifests _(as of Firefox 109)_, so it should also be possible to ship it there as well …

**Comment by bramus** [comment]
Work is being done in the https://github.com/bramus/mastodon-profile-redirect/tree/firefox branch. 

Doesn’t seem like it’ll work though. Getting back

```
$ web-ext run --firefox-preview
Running web extension from /Users/bramus/repos/projects/mastodon-profile-redirect/src
Configuring Firefox preferences for Manifest V3
Setting custom Firefox preferences: {
  "extensions.manifestV3.enabled": true
}
Use --verbose or --devtools to see logging

WebExtError: installTemporaryAddon: Error: Error: Could not install add-on at '/Users/bramus/repos/projects/mastodon-profile-redirect/src': Error: background.service_worker is currently disabled
    at RemoteFirefox.installTemporaryAddon (file:///Users/bramus/.nvm/versions/node/v18.12.1/lib/node_modules/web-ext/lib/firefox/remote.js:90:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FirefoxDesktopExtensionRunner.startFirefoxInstance (file:///Users/bramus/.nvm/versions/node/v18.12.1/lib/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:218:27)
    at async FirefoxDesktopExtensionRunner.run (file:///Users/bramus/.nvm/versions/node/v18.12.1/lib/node_modules/web-ext/lib/extension-runners/firefox-desktop.js:51:5)
    at async Promise.all (index 0)
    at async MultiExtensionRunner.run (file:///Users/bramus/.nvm/versions/node/v18.12.1/lib/node_modules/web-ext/lib/extension-runners/index.js:68:5)
    at async run (file:///Users/bramus/.nvm/versions/node/v18.12.1/lib/node_modules/web-ext/lib/cmd/run.js:178:3)
    at async Program.execute (file:///Users/bramus/.nvm/versions/node/v18.12.1/lib/node_modules/web-ext/lib/program.js:263:7)
    at async file:///Users/bramus/.nvm/versions/node/v18.12.1/lib/node_modules/web-ext/bin/web-ext.js:13:1
```

The [tracking bug to support `background.service_worker`](https://bugzilla.mozilla.org/show_bug.cgi?id=1609923) is still open.

https://github.com/mozilla/web-ext/issues/2379#issuecomment-1173745486 suggests to use a separate manifest for Firefox, using the old way …

**Comment by bramus** [comment]
After some trial and error I got it working: https://github.com/bramus/mastodon-profile-redirect/commit/2a2e17a322e7c1bd479d90c4ea6d402870d2c3f4

A build has been submitted, awaiting approval …

**Comment by bramus** [comment]
Extension has been approved and is now published: https://addons.mozilla.org/en-US/firefox/addon/mastodon-profile-redirect/

Note that it is only compatible with Firefox 109 and up due to the usage of Manifest v3. To make it work in Firefox prior to 107, [follow these instructions](https://github.com/bramus/mastodon-profile-redirect#firefox)
